import os
import exifread
import sys

def detect_ai_signature(tags: dict) -> tuple[bool, list[str]]:
    """
    EXIF etiketlerini analiz ederek bilinen AI araçlarının yazılım izlerini tespit eder.
    """
    ai_keywords = [
        "adobe firefly", "animegenius", "artbreeder", "astria", "automatic1111", 
        "bing image creator", "canva magic", "civitai", "clipdrop", "comfyui", 
        "craiyon", "dall-e", "dalle", "deepbrain", "deepdream", "deepfloyd", 
        "deforum", "dezgo", "dream by wombo", "dreamlike", "dreamstudio", 
        "ebsynth", "flux", "fooocus", "fotor ai", "gencraft", "gemini", 
        "getimg", "grok", "haiper", "heygen", "hotpot", "huggingface", 
        "ideogram", "imagen", "imagine with meta", "invokeai", "jasper art", 
        "kaiber", "kakarot", "kandinsky", "kling ai", "krea", "leonardo", 
        "let's enhance", "lexica", "luma ai", "mage.space", "magnific", 
        "maze.guru", "meta ai", "midjourney", "midjourney bot", "muse", 
        "neural.love", "nightcafe", "novelai", "openai", "openart", "parti", 
        "photoroom", "phygital", "pika", "pixai", "playgroundai", "prompthero", 
        "recraft", "remini", "replicate", "rudalle", "runway", "scenario", 
        "sd-webui", "sdxl", "seaart", "sinkin", "sora", "stable diffusion", 
        "stable video diffusion", "starryai", "stablediffusion", "synthesia", 
        "tensor.art", "topaz gigapixel", "topaz labs", "upscayl", "vanceai", 
        "vqgan", "wombo", "wuerstchen", "yodayo",
        "ai art", "ai generated", "ai-generated", "artificial intelligence", 
        "created with ai", "deep learning", "diffusion model", 
        "generated by ai", "generative adversarial network", "generative ai", 
        "generative fill", "img2img", "machine learning", "neural network", 
        "synthetic media", "synthography", "text-to-image", "txt2img",
        "a1111", "animate-diff", "cfg scale:", "clip skip:", "control module:", 
        "controlnet", "denoising strength:", "dreambooth", "face restoration:", 
        "hires steps:", "hires upscaler:", "hypernetwork", "lora:", 
        "model hash:", "negative prompt:", "prompt:", "sampler:", "seed:", 
        "steps:", "textual inversion", "vae:"
    ]
    
    critical_tags = [
        "Image Software", "Image CreatorTool", "EXIF UserComment", 
        "Image ImageDescription", "Image Make", "Image Model",
        "Software", "CreatorTool", "UserComment", "ImageDescription", "Make", "Model",
        "Image ProcessingSoftware", "Image Artist", "Image Copyright", 
        "Image DocumentName", "Image HostComputer", "Image ApplicationNotes",
        "EXIF MakerNote", "EXIF ImageUniqueID", "EXIF CameraOwnerName",
        "Image XPTitle", "Image XPComment", "Image XPAuthor", "Image XPSubject",
        "Image PrintIM", "Image Rating", "Image History"
    ]
    
    found_signatures = []
    for tag_name in critical_tags:
        if tag_name in tags:
            tag_value = str(tags[tag_name]).lower()
            for keyword in ai_keywords:
                if keyword in tag_value:
                    found_signatures.append(
                        f"Şüpheli iz '{keyword}', şu etikette bulundu: '{tag_name}' -> {tags[tag_name]}"
                    )
    return len(found_signatures) > 0, found_signatures

def analyze_metadata(file_path: str) -> dict:
    """
    Metadata çıkarımı yapar ve S2 gereksinimlerini karşılayan JSON sözlüğü döner.
    """
    result = {
        "success": False,
        "error_message": None,
        "file_path": file_path,
        "is_ai_detected": False,
        "ai_signatures_found": [],
        "extracted_metadata": {}
    }

    if not os.path.exists(file_path):
        err_msg = f"İncelenecek dosya bulunamadı -> {file_path}"
        print(f"Hata: {err_msg}")
        result["error_message"] = err_msg
        return result
        
    valid_extensions = {".jpg", ".jpeg", ".png"}
    _, ext = os.path.splitext(file_path)
    if ext.lower() not in valid_extensions:
        err_msg = f"Desteklenmeyen dosya formatı ({ext})."
        print(f"Hata: {err_msg}")
        result["error_message"] = err_msg
        return result
        
    try:
        with open(file_path, 'rb') as image_file:
            # S6 Entegrasyonu için details=False hız optimizasyonu [cite: 35, 42]
            tags = exifread.process_file(image_file, details=False)
            
        if not tags:
            err_msg = "Metadata Temizlenmiş/Yok"
            print(f"Uyarı: {err_msg} [cite: 71, 72]")
            result["error_message"] = err_msg
            return result
            
        print(f"\n--- Metadata Analiz Raporu: {file_path} ---")
        
        # Web arayüzü (Ufuk) için temiz sözlük yapısı [cite: 45, 147]
        clean_tags = {str(k): str(v) for k, v in tags.items() if k not in ('JPEGThumbnail', 'TIFFThumbnail')}
        result["extracted_metadata"] = clean_tags
        
        is_ai, signatures = detect_ai_signature(tags)
        result["is_ai_detected"] = is_ai
        result["ai_signatures_found"] = signatures
        result["success"] = True
        
        if is_ai:
            print("\n[!] Şüpheli Yazılım İzi Bulundu [!]")
            for sig in signatures:
                print(f" - {sig}")
        else:
            print("\n[+] Temiz: Bilinen bir AI aracı izine rastlanmadı.")
            
        # Temiz ve okunabilir bir çıktı (Clean Output) için bazı önemli etiketleri özetleyelim
        print("\nÖnemli Metadata Detayları:")
        important_tags = [
            "Image Make", "Image Model", "Image Software", 
            "Image DateTime", "EXIF ExifImageWidth", "EXIF ExifImageLength"
        ]
        
        for tag in important_tags:
            if tag in tags:
                print(f"{tag:<25}: {tags[tag]}")
                
        print("-------------------------------------------\n")
        return tags
        
    except Exception as e:
        print(f"Hata: Dosya işlenirken beklenmeyen bir sorun oluştu: {e}")
        return {}

if __name__ == "__main__":
    import os
    
    current_dir = os.path.dirname(os.path.abspath(__file__))
    base_dir = os.path.dirname(current_dir) 
    

    test_image_path = os.path.join(base_dir, "data", "raw", "Test.jpg")

    print(f"--- Analiz Başlatılıyor: {test_image_path} ---")
    
    if os.path.exists(test_image_path):
        analyze_metadata(test_image_path)
    else:
        print("Hata: Fotoğraf data/raw klasöründe bulunamadı!")